-- ============================================================
-- CUSTOMER BEHAVIOR ANALYSIS
-- Table: customer (loaded via the Python cleaning pipeline)
-- ============================================================

-- Q1) What is the total revenue generated by male vs. female customers?
SELECT
    GENDER,
    SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE
FROM
    CUSTOMER
GROUP BY
    GENDER;

-- Q2) Which customers used a discount but still spent more than the average purchase amount?
-- (fixed: original had a stray semicolon inside the subquery, causing a syntax error)
SELECT
    *
FROM
    CUSTOMER
WHERE
    DISCOUNT_APPLIED = 'Yes'
    AND PURCHASE_AMOUNT > (
        SELECT
            AVG(PURCHASE_AMOUNT)
        FROM
            CUSTOMER
    );

-- Q3) Which are the top 5 products with the highest average review rating?
SELECT
    ITEM_PURCHASED,
    ROUND(AVG(REVIEW_RATING::NUMERIC), 2) AS "Average Product Rating"
FROM
    CUSTOMER
GROUP BY
    ITEM_PURCHASED
ORDER BY
    AVG(REVIEW_RATING) DESC
LIMIT
    5;

-- Q4) Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    SHIPPING_TYPE,
    AVG(PURCHASE_AMOUNT) AS AVG_PURCHASE_AMOUNT
FROM
    CUSTOMER
WHERE
    SHIPPING_TYPE = 'Standard'
    OR SHIPPING_TYPE = 'Express'
GROUP BY
    1
ORDER BY
    2 DESC;

-- Q5) Do subscribed customers spend more? Compare average spend and total revenue.
SELECT
    SUBSCRIPTION_STATUS,
    COUNT(CUSTOMER_ID) AS NUM_CUSTOMERS,
    ROUND(AVG(PURCHASE_AMOUNT), 2) AS "avg_purchase",
    SUM(PURCHASE_AMOUNT) AS "total_purchase"
FROM
    CUSTOMER
GROUP BY
    1
ORDER BY
    3 DESC;

-- Q6) Which 5 products have the highest percentage of purchases with discounts applied?
SELECT
    ITEM_PURCHASED,
    ROUND(
        100 * SUM(
            CASE
                WHEN DISCOUNT_APPLIED = 'Yes' THEN 1
                ELSE 0
            END
        ) / COUNT(*),
        2
    ) AS DISCOUNT_RATE
FROM
    CUSTOMER
GROUP BY
    1
ORDER BY
    2 DESC
LIMIT
    5;

-- Q7) Segment customers into New, Returning, and Loyal based on total previous purchases,
-- and show the count of each segment.
WITH
    CUSTOMER_TYPE AS (
        SELECT
            CUSTOMER_ID,
            PREVIOUS_PURCHASES,
            CASE
                WHEN PREVIOUS_PURCHASES = 1 THEN 'New'
                WHEN PREVIOUS_PURCHASES BETWEEN 2 AND 10 THEN 'Returning'
                ELSE 'Loyal'
            END AS CUSTOMER_SEGMENT
        FROM
            CUSTOMER
    )
SELECT
    CUSTOMER_SEGMENT,
    COUNT(*) AS "Number of Customer"
FROM
    CUSTOMER_TYPE
GROUP BY
    1
ORDER BY
    2 DESC;

-- Q8) What are the top 3 most purchased products within each category?
WITH
    ITEM_COUNTS AS (
        SELECT
            CATEGORY,
            ITEM_PURCHASED,
            COUNT(*) AS TOTAL_ORDERS,
            ROW_NUMBER() OVER (
                PARTITION BY
                    CATEGORY
                ORDER BY
                    COUNT(*) DESC
            ) AS ITEM_RANK
        FROM
            CUSTOMER
        GROUP BY
            CATEGORY,
            ITEM_PURCHASED
    )
SELECT
    *
FROM
    ITEM_COUNTS
WHERE
    ITEM_RANK <= 3;

-- Q9) Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    COUNT(CUSTOMER_ID) AS NUM_CUSTOMERS,
    SUBSCRIPTION_STATUS
FROM
    CUSTOMER
WHERE
    PREVIOUS_PURCHASES >= 5
GROUP BY
    2;

-- Q10) What is the revenue contribution of each age group?
-- (fixed: original had a leftover "SELECT * FROM CUSTOMER" debug line before the real query,
--  which caused a syntax error since two SELECT statements can't run together like that)
SELECT
    SUM(PURCHASE_AMOUNT) AS TOTAL_REVENUE,
    AGE_GROUP
FROM
    CUSTOMER
GROUP BY
    2
ORDER BY
    1 DESC;
